
name: Java Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test on JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Resolve Dependencies, Plugins & Reports
        run: |
          mvn 
          dependency:go-offline 
          dependency:get 
            -Dartifact=org.apache.maven.plugins:maven-surefire-plugin:2.12.4 
            -Dartifact=org.apache.maven.plugins:maven-resources-plugin:2.6
      - name: test with maven
        run: mvn --batch-mode test